GET http://localhost:4000/

###
POST http://localhost:4000/api/register
Content-Type: application/json

{
    "email": "3333123",
    "password": "12e21a",
    "username": "t324",
    "fullname": "Tran Duc Vu",
    "gender": "Male"
}

###
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email": "trana2@gmail.com",
    "password": "1221a"
}

###
GET http://localhost:4000/api/users

###
POST http://localhost:4000/api/refresh_token

###
GET http://localhost:4000/api/access_token

###
GET http://localhost:4000/api/logout

###
POST http://localhost:4000/api/user 
Content-Type: application/json

{
    "searchValue": "tran"
}

###
GET http://localhost:4000/api/user/64a3ddae4a25ed34ebbf0da6

###
PATCH http://localhost:4000/api/user/64a3ddae4a25ed34ebbf0da6

###
GET http://localhost:4000/api/posts_discover

###
GET http://localhost:4000/api/suggested_users

###
POST http://localhost:4000/api/notification

###
POST http://localhost:4000/api/password/code
Content-Type: application/json

{
    "email": "vutranfake2@gmail.com"
}

###
POST http://localhost:4000/api/password/confirm_code
Content-Type: application/json

{
     "_id": "64f300623a47ac9e381bfe19",
     "email": "vutranfake2@gmail.com",
     "code": "9igvrj"
}

###
POST http://localhost:4000/api/password/reset
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQ2MDAxNjIsImV4cCI6MTY5NDYwMzc2Mn0.LmmHu5chH-PyR0Wg9FHn3Srh6zL-03fhs4CrQyr47CI", 
    "newPassword": "123456789"
}


